#	vivado -mode tcl -source simulate_iualgnchk.tcl
#	vivado -mode tcl -source simulate_iualu.tcl
#	vivado -mode tcl -source simulate_iubprc.tcl
#	vivado -mode tcl -source simulate_iucall.tcl
#	vivado -mode tcl -source simulate_iucc.tcl
#	vivado -mode tcl -source simulate_iucmp.tcl
#	vivado -mode tcl -source simulate_iucond.tcl
#	vivado -mode tcl -source simulate_iuctrl.tcl
# iudmem.vhd
#	vivado -mode tcl -source simulate_iuet.tcl
# iuexln.vhd
#	vivado -mode tcl -source simulate_iuexma.tcl
# iuexstg.vhd
#	vivado -mode tcl -source simulate_iufmt0dec.tcl
#	vivado -mode tcl -source simulate_iufmt1dec.tcl
#	vivado -mode tcl -source simulate_iufmt2dec.tcl
#	vivado -mode tcl -source simulate_iufmt3dec.tcl
#	vivado -mode tcl -source simulate_iufwpastu.tcl
#	vivado -mode tcl -source simulate_iufwpast.tcl
#	vivado -mode tcl -source simulate_iufwpreu.tcl
#	vivado -mode tcl -source simulate_iufwpre.tcl
#	vivado -mode tcl -source simulate_iuhdu.tcl
#	vivado -mode tcl -source simulate_iuidex.tcl
# iuidln.vhd
# iuidstg.vhd
#	vivado -mode tcl -source simulate_iuifid.tcl
# iuifln.vhd
# iuifstg.vhd
# iuimem.vhd
#	vivado -mode tcl -source simulate_iuintrdec.tcl
#	vivado -mode tcl -source simulate_iuintr.tcl
#	vivado -mode tcl -source simulate_iuld.tcl
# iumaln.vhd
# iumastg.vhd
#	vivado -mode tcl -source simulate_iumawb.tcl
#	vivado -mode tcl -source simulate_iumul32post.tcl
#	vivado -mode tcl -source simulate_iumul32pre.tcl
#	vivado -mode tcl -source simulate_iumul32reg.tcl
#	vivado -mode tcl -source simulate_iupc.tcl
#	vivado -mode tcl -source simulate_iupil.tcl
#	vivado -mode tcl -source simulate_iurett.tcl
#	vivado -mode tcl -source simulate_iurfport.tcl
#	vivado -mode tcl -source simulate_iurfreg.tcl
#	vivado -mode tcl -source simulate_iurf.tcl
#	vivado -mode tcl -source simulate_iuschk.tcl
#	vivado -mode tcl -source simulate_iusft.tcl
#	vivado -mode tcl -source simulate_iustdo.tcl
#	vivado -mode tcl -source simulate_iustdqm.tcl
#	vivado -mode tcl -source simulate_iust.tcl
#	vivado -mode tcl -source simulate_ius.tcl
#
simulate:
	vivado -mode tcl -source ./tcl/simulate_iuintr.tcl

clean:
	rm -rf *.cache
	rm -rf *.hw
	rm -rf *.ip_user_files
	rm -rf *.sim
	rm -rf *.xpr
	rm -rf *.jou *.log












































