# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/masaya/Share/Helios/Projects/CmodA7/project_1/project_1.runs/synth_1/iu.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/masaya/Share/Helios/Projects/CmodA7/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/masaya/Share/Helios/Projects/CmodA7/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.2 [current_project]
set_property ip_output_repo /home/masaya/Share/Helios/Projects/CmodA7/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  /home/masaya/Share/Helios/iu/iu_pac.vhd
  /home/masaya/Share/Helios/iu/iuintr_pac.vhd
  /home/masaya/Share/Helios/iu/iuhdu_pac.vhd
  /home/masaya/Share/Helios/iu/iufwu_pac.vhd
  /home/masaya/Share/Helios/iu/iuifid_pac.vhd
  /home/masaya/Share/Helios/iu/iuidex_pac.vhd
  /home/masaya/Share/Helios/iu/iuexma_pac.vhd
  /home/masaya/Share/Helios/iu/iumawb_pac.vhd
  /home/masaya/Share/Helios/iu/iumul32_pac.vhd
  /home/masaya/Share/Helios/iu/iuifln_pac.vhd
  /home/masaya/Share/Helios/iu/iuidln_pac.vhd
  /home/masaya/Share/Helios/iu/iuexln_pac.vhd
  /home/masaya/Share/Helios/iu/iumaln_pac.vhd
  /home/masaya/Share/Helios/iu/iuldst_pac.vhd
  /home/masaya/Share/Helios/iu/iualgnchk.vhd
  /home/masaya/Share/Helios/iu/iualgnchk_pac.vhd
  /home/masaya/Share/Helios/iu/iualu_pac.vhd
  /home/masaya/Share/Helios/iu/iualu.vhd
  /home/masaya/Share/Helios/iu/iuctrl_pac.vhd
  /home/masaya/Share/Helios/iu/iubprc_pac.vhd
  /home/masaya/Share/Helios/iu/iubprc.vhd
  /home/masaya/Share/Helios/iu/iucall_pac.vhd
  /home/masaya/Share/Helios/iu/iucall.vhd
  /home/masaya/Share/Helios/iu/iucc_pac.vhd
  /home/masaya/Share/Helios/iu/iucc.vhd
  /home/masaya/Share/Helios/iu/iucmp_pac.vhd
  /home/masaya/Share/Helios/iu/iucmp.vhd
  /home/masaya/Share/Helios/iu/iucond_pac.vhd
  /home/masaya/Share/Helios/iu/iucond.vhd
  /home/masaya/Share/Helios/iu/iufmt0dec_pac.vhd
  /home/masaya/Share/Helios/iu/iufmt1dec_pac.vhd
  /home/masaya/Share/Helios/iu/iufmt2dec_pac.vhd
  /home/masaya/Share/Helios/iu/iufmt3dec_pac.vhd
  /home/masaya/Share/Helios/iu/iuintrdec_pac.vhd
  /home/masaya/Share/Helios/iu/iuctrl.vhd
  /home/masaya/Share/Helios/iu/iuet_pac.vhd
  /home/masaya/Share/Helios/iu/iuet.vhd
  /home/masaya/Share/Helios/iu/iuexstg_pac.vhd
  /home/masaya/Share/Helios/iu/iuexln.vhd
  /home/masaya/Share/Helios/iu/iuexma.vhd
  /home/masaya/Share/Helios/iu/iusft_pac.vhd
  /home/masaya/Share/Helios/iu/iuexstg.vhd
  /home/masaya/Share/Helios/iu/iurf_pac.vhd
  /home/masaya/Share/Helios/iu/iufmt0dec.vhd
  /home/masaya/Share/Helios/iu/iufmt1dec.vhd
  /home/masaya/Share/Helios/iu/iufmt2dec.vhd
  /home/masaya/Share/Helios/iu/iufmt3dec.vhd
  /home/masaya/Share/Helios/iu/iufwpast.vhd
  /home/masaya/Share/Helios/iu/iufwpastu.vhd
  /home/masaya/Share/Helios/iu/iufwpre.vhd
  /home/masaya/Share/Helios/iu/iufwpreu.vhd
  /home/masaya/Share/Helios/iu/iuhdu.vhd
  /home/masaya/Share/Helios/iu/iuidex.vhd
  /home/masaya/Share/Helios/iu/iuidstg_pac.vhd
  /home/masaya/Share/Helios/iu/iuidln.vhd
  /home/masaya/Share/Helios/iu/iuidstg.vhd
  /home/masaya/Share/Helios/iu/iuifid.vhd
  /home/masaya/Share/Helios/iu/iupc_pac.vhd
  /home/masaya/Share/Helios/iu/iuifstg_pac.vhd
  /home/masaya/Share/Helios/iu/iuifln.vhd
  /home/masaya/Share/Helios/iu/iurett_pac.vhd
  /home/masaya/Share/Helios/iu/iuifstg.vhd
  /home/masaya/Share/Helios/iu/iuintr.vhd
  /home/masaya/Share/Helios/iu/iuintrdec.vhd
  /home/masaya/Share/Helios/iu/iuld.vhd
  /home/masaya/Share/Helios/iu/iumastg_pac.vhd
  /home/masaya/Share/Helios/iu/iuschk_pac.vhd
  /home/masaya/Share/Helios/iu/ius_pac.vhd
  /home/masaya/Share/Helios/iu/iupil_pac.vhd
  /home/masaya/Share/Helios/iu/iumaln.vhd
  /home/masaya/Share/Helios/iu/iumastg.vhd
  /home/masaya/Share/Helios/iu/iumawb.vhd
  /home/masaya/Share/Helios/iu/iumul32post.vhd
  /home/masaya/Share/Helios/iu/iumul32pre.vhd
  /home/masaya/Share/Helios/iu/iumul32reg.vhd
  /home/masaya/Share/Helios/iu/iupc.vhd
  /home/masaya/Share/Helios/iu/iupil.vhd
  /home/masaya/Share/Helios/iu/iurett.vhd
  /home/masaya/Share/Helios/iu/iurfreg_pac.vhd
  /home/masaya/Share/Helios/iu/iurfport_pac.vhd
  /home/masaya/Share/Helios/iu/iurf.vhd
  /home/masaya/Share/Helios/iu/iurfport.vhd
  /home/masaya/Share/Helios/iu/iurfreg.vhd
  /home/masaya/Share/Helios/iu/ius.vhd
  /home/masaya/Share/Helios/iu/iuschk.vhd
  /home/masaya/Share/Helios/iu/iusft.vhd
  /home/masaya/Share/Helios/iu/iustdqm_pac.vhd
  /home/masaya/Share/Helios/iu/iustdo_pac.vhd
  /home/masaya/Share/Helios/iu/iust.vhd
  /home/masaya/Share/Helios/iu/iustdo.vhd
  /home/masaya/Share/Helios/iu/iustdqm.vhd
  /home/masaya/Share/Helios/iu/iu.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/masaya/Share/Helios/Projects/CmodA7/project_1/project_1.srcs/utils_1/imports/synth_1/iu.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top iu -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef iu.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file iu_utilization_synth.rpt -pb iu_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
